Add template for pull request
kristinejosami/first-git-project pull request #5
Opened 2020-08-19 16:14 UTC by naokitcut

# Description

We can create a template for pull request, and I made it 😄 

https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

2020-08-19 16:23 UTC, naokitcut commented
Can you check the template I made, and please approve it if it's okay

2020-08-19 16:26 UTC, naokitcut commented
Here's how to approve.
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/approving-a-pull-request-with-required-reviews

 Of course, if you wanna ask something, or there's problem about my code, please don't `Approve` it. Please `Comment` or `Request Change` instead.

2020-08-20 16:20 UTC, kristinejosami requested changes
kindly convert the template's name to small letters(snakecase)

2020-08-20 16:20 UTC, kristinejosami commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] My code follows the style guidelines of this project(Expample)
please correct the spelling of the word "(Expample)" to (Example)"

2020-08-20 16:43 UTC, kristinejosami commented
> # Description
> We can create a template for pull request, and I made it 😄
> 
> https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

I wanna use emoji when replying. Is it built in to your keyboard? hahahahaha I know it isn't but where can I see emoji icon on github?

2020-08-20 16:48 UTC, kristinejosami commented
> > # Description
> > We can create a template for pull request, and I made it 😄
> > https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository
> 
> I wanna use emoji when replying. Is it built in to your keyboard? hahahahaha I know it isn't but where can I see emoji icon on github?

😄 ❤️ 😆 🤣 HAHAHAHAHAHAHAHAHA I searched it. I wanna insert emojis to convey my feelings when writing a message lol. 😆 🤣 😚 😍 😝 💩 
https://gist.github.com/rxaviers/7360908

2020-08-22 13:42 UTC, naokidney commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] My code follows the style guidelines of this project(Expample)
Good joooob 😭

2020-08-22 14:06 UTC, naokidney commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] My code follows the style guidelines of this project(Expample)
Usually, I'm the one who fix this. But this time, can you please give me a suggested change?
https://haacked.com/archive/2019/06/03/suggested-changes/

2020-08-22 14:06 UTC, naokidney commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] My code follows the style guidelines of this project(Expample)
@kristinejosami

2020-08-23 12:30 UTC, kristinejosami commented on .github/pull_request_template.md
> +- [ ] My code follows the style guidelines of this project(Expample)
```suggestion
- print("My code follows the style guidelines of this project(Example)")
```

2020-08-23 12:34 UTC, naokidney commented on .github/pull_request_template.md
> +- [ ] My code follows the style guidelines of this project(Expample)
@kristinejosami  Oh, sorry, I'm using markdown...
Can you check it and give me another suggestion?

https://guides.github.com/features/mastering-markdown/

2020-08-23 13:42 UTC, kristinejosami commented on .github/pull_request_template.md
> +- [ ] My code follows the style guidelines of this project(Expample)
```suggestion
- [ ] My code follows the style guidelines of this project(Example) 
```

2020-08-23 14:10 UTC, naokidney commented
@kristinejosami please review again 😸

2020-08-24 03:15 UTC, kristinejosami commented on .github/pull_request_template.md
> +- [ ] My code follows the style guidelines of this project(Example)
```suggestion
- [ ] My code follows the style guidelines of this project example
```

2020-08-24 14:07 UTC, kristinejosami commented on .github/pull_request_template.md
> +- [ ] My code follows the style guidelines of this project(Example)
@naokitcut please check 😸

2020-08-25 16:28 UTC, kristinejosami commented
LGTM 👍

2020-08-25 16:29 UTC, kristinejosami reviewed
LGTM 👍

2020-08-29 01:28 UTC, naokitcut commented
@kristinejosami can you approved it, not comment 😄

2020-08-29 09:01 UTC, kristinejosami approved these changes

2020-08-29 10:43 UTC, naokitcut commented
@kristinejosami Thankies 😄

2020-08-29 10:43 UTC, merged